### ISSUE TITLE
'Default' annotation does not work on client side

### ISSUE THREAD

**Issue by pvangool** [dnault/therapi-json-rpc#3]
Not sure if you ever intended this to work ;-). Or if it even can.

The '@Default' annotation can be used in 'remotable' service interfaces. On the server side that works fine. But if you try to use that same interface with the service factory on the client side, it does not.

**Comment by dnault** [comment]
I wouldn't expect that annotation to have any effect on the client side. Is the presence of the annotation breaking something, or is it surprising that it has no effect?

**Comment by pvangool** [comment]
Suppose I have an interface like:

public interface CalculatorService {
    void add(Integer arg1, Integer arg2, @Default boolean makeItSpecial);
}

So from a  client I then should be able to call:

client.calculatorService().add(1, 2);
client.calculatorService().add(1, 2, false);
client.calculatorService().add(1, 2, true);

But the first one is not allowed since it is not seen as an optional argument. To support that I would have to define the client interface as:

public interface CalculatorService {
    void add(Integer arg1, Integer arg2);
    void add(Integer arg1, Integer arg2, boolean makeItSpecial);
}

But thinking about this ticket a bit more, what I am asking becomes impossible for a client to do if there is more than 1 ‘Default’ argument.

So I think we can close this ticket.

Thanks.

Paul

> On May 27, 2016, at 4:25 PM, dnault <notifications@github.com> wrote:
> 
> I wouldn't expect that annotation to have any effect on the client side. Is the presence of the annotation breaking something, or is it surprising that it has no effect?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/dnault/therapi-json-rpc/issues/3#issuecomment-222273751>, or mute the thread <https://github.com/notifications/unsubscribe/AA6HQx9FWhAxtJILshNuNAz5YPaTzdy1ks5qF31egaJpZM4Io7AH>.
> 

--
Paul van Gool
pvangool@gmail.com
