### ISSUE TITLE
Support for named parameters in service factory

### ISSUE THREAD

**Issue by pvangool** [dnault/therapi-json-rpc#4]
I'm using the service factory for developing a client. But it results in 'positional/anonymous arguments' instead of 'named arguments'.

Can you consider adding support for named parameters through the service factory?

**Comment by dnault** [comment]
Added a `setUsedNamedArguments` method to Service factory. Defaults to false unless set.

Thanks for the suggestion.

**Comment by pvangool** [comment]
Thanks!
